apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: roboshop
  labels: 
    name: roboshop
    env: dev
spec:
  containers:
  - name: debug
    image: balaji1729/debug:v1
    imagePullPolicy: Always