apiVersion: v1
kind: pod
metadata:
  name: debug
  namespace: roboshop
  labels: 
    name: roboshop
    emv: dev
spec:
  container:
  - name: debug
    image: balaji1729/debug:v1
    imagePullPolicy: Always