apiVersion: v1
kind: configMap
metadata:
  name: shipping-configmap
data:
  CART_ENDPOINT: cart:8080
  DB_HOST: mysql
---
apiVersion: v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    name: roboshop
    env: dev
    running: shipping
spec: 
  replicas: 1
  selector:
    matchLabels:
      name: roboshop
      env: dev
      running: shipping
  template:
    metadata:
      labels:
        name: roboshop
        env: dev
        running: shipping
  spec:
    containers:
    - name: shipping
      image: balaji1729/shipping
      imagePullPolicy: Always
      ports:
      - protocal: TCP
        port: 8080
        targetport: 8080
      envForm:
      - configMapRef:
          name: shipping-configmap 
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
spec:
  type: ClusterIp
  selector:
    matchLabels:
      name: roboshop
      env: dev
      running: shipping
  template:
    metadata:
      labels:
        name: roboshop
        env: dev
        running: shipping